ARG REGISTRY_PREFIX=docker.m.daocloud.io
FROM ${REGISTRY_PREFIX}/library/node:22-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm config set registry https://registry.npmmirror.com
RUN npm install
COPY . .
RUN npm run build

ARG REGISTRY_PREFIX=docker.m.daocloud.io
FROM ${REGISTRY_PREFIX}/library/nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
